{
 "title": "ec2-teste-kong-dbless-api-overview",
 "tags": [
  "ec2_ingress",
  "teste-kong-dbless-api",
  "vkpr"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "container",
    "query": {
     "query": "label_values(kube_node_info{origin_prometheus=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "origin_prometheus",
    "label": "K8S",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kubernetes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=\"teste-kong-dbless-api\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"teste-kong-dbless-api\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{cluster=\"teste-kong-dbless-api\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubernetes_build_info{cluster=\"teste-kong-dbless-api\"}",
     "legendFormat": "{{ git_version }}"
    }
   ]
  },
  {
   "title": "ETCD Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "etcd_server_version{cluster=\"teste-kong-dbless-api\"}",
     "legendFormat": "{{ server_version }}"
    }
   ]
  },
  {
   "title": "ETCD servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(etcd_server_version{cluster=\"teste-kong-dbless-api\"})"
    }
   ]
  },
  {
   "title": "Abnormal Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_node_status_condition{cluster=\"teste-kong-dbless-api\",condition=\"Ready\", status!=\"true\"} == 1) OR ON(node) (kube_node_status_condition{condition!=\"Ready\", status=\"true\"} == 1)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Abnormal Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_status_phase{cluster=\"teste-kong-dbless-api\",phase!~\"Running|Succeeded\"} == 1) OR ON(namespace, pod) (kube_pod_status_ready{condition=\"true\"} == 0)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Abnormal Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{cluster=\"teste-kong-dbless-api\"} != 1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Container Runtime Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, kube_node_info{cluster=\"teste-kong-dbless-api\"})",
     "legendFormat": "{{ container_runtime_version }}"
    }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, kubernetes_build_info{cluster=\"teste-kong-dbless-api\"})",
     "legendFormat": "{{ platform }}"
    }
   ]
  },
  {
   "title": "Leaderless ETCD servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(etcd_server_has_leader{cluster=\"teste-kong-dbless-api\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{cluster=\"teste-kong-dbless-api\",instance!=\"\"}) - sum (node_filesystem_free_bytes{cluster=\"teste-kong-dbless-api\",instance!=\"\"})) / sum (node_filesystem_size_bytes{cluster=\"teste-kong-dbless-api\",instance!=\"\"})"
    }
   ]
  },
  {
   "title": "$Node： Node memory details ",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"teste-kong-dbless-api\"}) by (node)",
     "legendFormat": "pod core "
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=\"teste-kong-dbless-api\",container!=\"\"}[2m])) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"teste-kong-dbless-api\",resource=\"cpu\", unit=\"core\",node!=\"\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"teste-kong-dbless-api\",resource=\"cpu\", unit=\"core\",node!=\"\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"teste-kong-dbless-api\",container!=\"\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=\"teste-kong-dbless-api\",resource=\"memory\", unit=\"byte\"}) by (node) - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"teste-kong-dbless-api\",resource=\"memory\", unit=\"byte\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"teste-kong-dbless-api\",resource=\"memory\", unit=\"byte\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{cluster=\"teste-kong-dbless-api\",device=~\"^/dev/.*$\",id=\"/\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{cluster=\"teste-kong-dbless-api\",device=~\"^/dev/.*$\",id=\"/\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"teste-kong-dbless-api\",container!=\"\"})by (node) / sum(kube_node_status_allocatable{cluster=\"teste-kong-dbless-api\",resource=\"memory\", unit=\"byte\"})by (node)",
     "legendFormat": " memory request %"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"teste-kong-dbless-api\",resource=\"memory\", unit=\"byte\"})by (node) / sum(kube_node_status_allocatable{cluster=\"teste-kong-dbless-api\",resource=\"memory\", unit=\"byte\"})by (node)",
     "legendFormat": " Memory Usage %"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"teste-kong-dbless-api\",resource=\"memory\", unit=\"byte\"})by (node) / sum(kube_node_status_allocatable{cluster=\"teste-kong-dbless-api\",resource=\"memory\", unit=\"byte\"})by (node)",
     "legendFormat": " Network bandwidth %"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=\"teste-kong-dbless-api\",container!=\"\"}[2m]))by (node) / sum(kube_node_status_allocatable{cluster=\"teste-kong-dbless-api\",resource=\"cpu\", unit=\"core\"})by (node)",
     "legendFormat": "CPU limit %"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"teste-kong-dbless-api\",resource=\"cpu\", unit=\"core\"})by (node) / sum(kube_node_status_allocatable{cluster=\"teste-kong-dbless-api\",resource=\"cpu\", unit=\"core\"})by (node)",
     "legendFormat": "CPU max %"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"teste-kong-dbless-api\",resource=\"cpu\", unit=\"core\"})by (node) / sum(kube_node_status_allocatable{cluster=\"teste-kong-dbless-api\",resource=\"cpu\", unit=\"core\"})by (node)",
     "legendFormat": " Network bandwidth %"
    },
    {
     "expr": "sum (container_fs_usage_bytes{cluster=\"teste-kong-dbless-api\",device=~\"^/dev/.*$\",id=\"/\"})by (node) / sum (container_fs_limit_bytes{cluster=\"teste-kong-dbless-api\",device=~\"^/dev/.*$\",id=\"/\"})by (node)",
     "legendFormat": " English version %"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=\"teste-kong-dbless-api\",resource=\"pods\", unit=\"integer\"})by (node)",
     "legendFormat": "Pod disk "
    }
   ]
  }
 ]
}