apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "teste-kong-dbless-api"
  environment:
    cluster_type: ec2
    domain: vkpr.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: staging
    grafana_obs_api: https://grafana.asdasd.vkpr.platform.vee.codes
    public_ip: 54.211.181.138
  annotations:
    backstage.io/kubernetes-id: "teste-kong-dbless-api"
    github.com/project-slug: veecode-homolog/teste-kong-dbless-api
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$54.211.181.138 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$54.211.181.138:~/.kube/config ~/.kube/config-teste-kong-dbless-api\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"54.211.181.138\")' -i ~/.kube/config-teste-kong-dbless-api\n  export KUBECONFIG=~/.kube/config-teste-kong-dbless-api\n  kubectl get pods -A\n"
    veecode/cluster-name: teste-kong-dbless-api
    kubernetes.io/secret-name: teste-kong-dbless-api-secret
    kubernetes.io/secret-namespace: veecode-homolog
    kubernetes.io/auth-provider: custom
    kubernetes.io/api-server: https://54.211.181.138:6550
    kubernetes.io/skip-tls-verify: "true"
    kubernetes.io/skip-metrics-lookup: "false"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
